version: "3.9"
services:
  proxy:
    image: nginx
    ports:
      - 80:80
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf:ro

  webapp:
    image: node
    volumes:
      - .:/app
    working_dir: /app
    environment:
      - API=http://localhost/webapi:80
    entrypoint: node
    command: ["webserver.js", "80"]

  webapi1:
    image: node
    volumes:
      - .:/app
    working_dir: /app
    entrypoint: node
    command: ["apiserver.js", "80"]

  webapi2:
    image: node
    volumes:
      - .:/app
    working_dir: /app
    entrypoint: node
    command: ["apiserver.js", "80"]
