version: "3.9"
services:
  proxy:
    image: nginx
    ports:
      - 80:80
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf:ro

  webapp:
    image: node
    volumes:
      - .:/app
    working_dir: /app
    environment:
      - API=http://localhost/2:80
    entrypoint: node
    command: ["webserver.js", "4000"]
    ports:
      - 4000:4000

  webapi1:
    image: node
    volumes:
      - .:/app
    working_dir: /app
    entrypoint: node
    command: ["apiserver.js", "3000"]
    ports:
      - 8081:3000

  webapi2:
    image: node
    volumes:
      - .:/app
    working_dir: /app
    entrypoint: node
    command: ["apiserver.js", "3000"]
    ports:
      - 8080:3000
